# Generated by Django 4.2.13 on 2024-06-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('certificate_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
